### ISSUE TITLE
Error getting 'propagate' from config

### ISSUE THREAD

**Issue by lizziel** [Goddard-Fortran-Ecosystem/pFlogger#54]
I am testing GCHP with library updates, specifically pFlogger v1.5.0 with MAPL 2.6.4, yaFyaml v0.5.0, gFTL-shared v1.2.0, and GMAO_Shared v1.3.8. I am running into an error in pFlogger that causes the program to fail very early in the run. My temporary workaround is to comment out setting `cap_options%logging_config` in main (`GCHPctm.F90`). After verifying all results look okay after the library updates I am turning my attention back to this pFlogger issue.

The logger yaml file I am using is [here](https://github.com/geoschem/geos-chem/pull/595/commits/b18c2b3f58b01ff06eecf5a9d7bfa8d1f3fb299b). It was originally provided by @tclune for use with MAPL v2.5.0. I am not sure which pFlogger version it went with.

This is the stdout message:
`/n/home08/elundgren/testruns/features/update_gmao_libraries/gchp_TransportTracer_gfortran83/CodeDir/src/pFlogger/src/Config.F90         931`

This is the stderr message:
```
FAIL at line=00103    get_value.inc                            <Type of request does not match type in config.>
STOP 1
```

Here is a [link to the code](https://github.com/Goddard-Fortran-Ecosystem/pFlogger/blob/50996b386a987f66b1343b1cd39c7d7bb8d42e08/src/Config.F90#L930-L931) where the error is caught. It is getting 'propagate' from the config object.

Do you know what the issue is? I suspect it is something in `logging.yaml` but am not yet familiar with configuring pFlogger.

**Comment by mathomp4** [comment]
Interesting. That `logging.yaml` looks like the one we are using in GEOS with an extra chunk:
```yaml
    CAP.EXTDATA:
        handlers: [mpi_shared]
        level: WARNING
        root_level: WARNING
        propagate: 0
```
I just tried it with GEOS and it works for me. Now, GEOS is still using pFlogger v1.4.5 because moving to the GFE Namespace (`PFLOGGER::pflogger` in CMake) is a bit more involved for us, so you are triggering one of the new return code statuses we don't have.

@lizziel can you try changing the `propagate` value to `false`:
```yaml
        propagate: false
```
I'm not the expert @tclune is, but `propagate` in pFlogger seems to want a logical, and maybe 0 isn't strictly acceptable as a logical.

**Comment by lizziel** [comment]
That fixed it. Thank you!
