### ISSUE TITLE
Test error with pFlogger 1.2.0 on Darwin: malloc error

### ISSUE THREAD

**Issue by mathomp4** [Goddard-Fortran-Ecosystem/pFlogger#6]
After fixing #5 by setting the free line length to `none` I then ran a `make tests` and:

```
[100%] Run tests.x
................................................................................
................................................................................
..........................................................tests.x(31045,0x7fff97764380) malloc: *** mach_vm_map(size=140619808788480) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
```
I'm not sure how to get more verbose output, but let me know and I'll do it.

**Comment by tclune** [comment]
Wow - have completely been missing mail from this repo.    To see more verbose output, you manually execute the test executable with the -d option.   Since some involve MPI, you need to launch with MPI.  
Probably something like

```script
mpirun -np 6 ./tests/tests.x -d
```

But I'm also now remembering that I did something clever with the tests where I was mocking MPI, so maybe you don't need the mpirun at all.
